functionsDirectory = "E:\\STA-CRM-6.0\\.netlify\\functions"
functionsDirectoryOrigin = "config"
headersOrigin = "config"
redirectsOrigin = "config"

[build]
publish = "E:\\STA-CRM-6.0\\.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':!server/'"
functions = "E:\\STA-CRM-6.0\\.netlify\\functions"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "20"
NPM_VERSION = "10"
NODE_ENV = "production"
NEXT_PUBLIC_SITE_ENV = "development"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
included_files = ["server/src/**"]
node_bundler = "esbuild"

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]